name: stats100
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - pip:
    - requests
    - pandas
    - lxml
    - beautifulsoup4
    - html5lib
    - openpyxl
    - tqdm
